name: workout_timer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  uuid: ^3.0.4
  flutter_tts: 3.2.0
  audioplayers: ^0.19.1
  validators: ^3.0.0
  numberpicker: ^2.1.1
  localstorage: ^4.0.0+1
  json_annotation: ^4.1.0
  json_serializable: ^5.0.0
  line_icons: ^2.0.1
  shared_preferences: ^2.0.6
  google_mobile_ads: ^0.13.2+1
  in_app_purchase: ^1.0.6
  package_info_plus: ^1.0.4
  fluttertoast: ^8.0.8
  wakelock: ^0.5.2

dev_dependencies:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/rubik/Rubik-SemiBold.ttf
        - asset: fonts/rubik/Rubik-Medium.ttf
        - asset: fonts/rubik/Rubik-ExtraBold.ttf
        - asset: fonts/rubik/Rubik-Regular.ttf
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-SemiBold.ttf
        - asset: fonts/inter/Inter-ExtraBold.ttf
        - asset: fonts/inter/Inter-Regular.ttf
